import type { SettlementService, SettlementType } from './types'

export const settlementTypeData: SettlementType[] = [
  {
    name: 'Military camp',
    type: 'military',
    minPopulation: 5,
    maxPopulation: 20,
    ratio: 0.5,
    hostileChance: 0.15,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 1, noEventRange: 1 },
  },
  {
    name: 'Caravan',
    type: 'traders',
    minPopulation: 2,
    maxPopulation: 20,
    ratio: 0.5,
    hostileChance: 0.05,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 1, noEventRange: 1 },
  },
  {
    name: 'Cottage',
    type: 'lifeplace',
    minPopulation: 1,
    maxPopulation: 10,
    ratio: 3,
    hostileChance: 0.15,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 1, noEventRange: 1 },
  },
  {
    name: 'Large encampment',
    type: 'military',
    minPopulation: 50,
    maxPopulation: 100,
    ratio: 1,
    hostileChance: 0.1,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 2, noEventRange: 1 },
  },
  {
    name: 'Hamlet',
    type: 'lifeplace',
    minPopulation: 50,
    maxPopulation: 150,
    ratio: 2.5,
    hostileChance: 0.1,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 3, noEventRange: 1 },
  },
  {
    name: 'Work crew (eg: woodcutters, miners, farmers)',
    type: 'traders',
    minPopulation: 50,
    maxPopulation: 200,
    ratio: 1,
    hostileChance: 0.1,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 2, noEventRange: 1 },
  },
  {
    name: 'Stationed garrison',
    type: 'military',
    minPopulation: 100,
    maxPopulation: 300,
    ratio: 1,
    hostileChance: 0.1,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 4, noEventRange: 2 },
  },
  {
    name: 'Fort',
    type: 'military',
    minPopulation: 200,
    maxPopulation: 400,
    ratio: 0.75,
    hostileChance: 0.1,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 5, noEventRange: 2 },
  },
  {
    name: 'Village',
    type: 'lifeplace',
    minPopulation: 300,
    maxPopulation: 1200,
    ratio: 2,
    hostileChance: 0.1,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 5, noEventRange: 1 },
  },
  {
    name: 'Encamped Army',
    type: 'military',
    minPopulation: 1000,
    maxPopulation: 3000,
    ratio: 0.25,
    hostileChance: 0.1,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 3, noEventRange: 2 },
  },
  {
    name: 'Refugee encampment',
    type: 'lifeplace',
    minPopulation: 300,
    maxPopulation: 5000,
    ratio: 0.15,
    hostileChance: 0.1,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 2, noEventRange: 1 },
  },
  {
    name: 'Town',
    type: 'lifeplace',
    minPopulation: 1000,
    maxPopulation: 6000,
    ratio: 1,
    hostileChance: 0.1,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 4, noEventRange: 1 },
  },
  {
    name: 'City',
    type: 'lifeplace',
    minPopulation: 4000,
    maxPopulation: 15000,
    ratio: 0.5,
    hostileChance: 0.04,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 5, noEventRange: 2 },
  },
  {
    name: 'Capital',
    type: 'lifeplace',
    minPopulation: 12000,
    maxPopulation: 50000,
    ratio: 0.1,
    hostileChance: 0.01,
    predominantRace: 'human',
    worldMapType: 'unmarked',
    worldMapRadiuses: { noSettlementRange: 6, noEventRange: 2 },
  },
]

export const settlementServicesBySize = [
  { id: 0, name: 'Inn / Tavern', ratios: [10, 8, 6, 4, 2, 1] },
  { id: 1, name: 'Adventuring Supplies', ratios: [17, 14, 10, 5, 2, 1] },
  { id: 2, name: 'Animals and Mounts', ratios: [12, 11, 9, 7, 5, 3] },
  { id: 3, name: 'Books and Maps', ratios: [18, 17, 15, 13, 11, 9] },
  { id: 4, name: 'Jewelry trader', ratios: [20, 19, 18, 16, 14, 12] },
  { id: 5, name: 'Armourer', ratios: [18, 16, 14, 12, 10, 8] },
  { id: 6, name: 'Bank', ratios: [17, 15, 13, 10, 8, 6] },
  { id: 7, name: 'Finesmith', ratios: [18, 17, 15, 13, 11, 9] },
  { id: 8, name: 'Tailor', ratios: [15, 13, 11, 10, 8, 6] },
  { id: 9, name: 'Potions, poisons, herbs', ratios: [18, 17, 16, 14, 12, 10] },
  { id: 10, name: 'Religious idols & Blessings', ratios: [16, 15, 13, 11, 9, 7] },
  { id: 11, name: 'Food & drink seller', ratios: [14, 12, 10, 8, 6, 4] },
  { id: 12, name: 'Temple', ratios: [16, 14, 12, 10, 8, 6] },
  { id: 13, name: 'Spell tomes and scrolls', ratios: [20, 19, 17, 15, 13, 11] },
  { id: 14, name: 'Thieving supplies', ratios: [19, 18, 16, 14, 12, 10] },
  { id: 15, name: 'Weapons Shop', ratios: [17, 15, 13, 11, 9, 7] },
  { id: 16, name: 'Vehicles and transportation', ratios: [15, 12, 13, 10, 8, 6] },
  { id: 17, name: "Adventurer's Guild", ratios: [19, 18, 16, 14, 12, 10] },
  { id: 18, name: 'Magic Items', ratios: [25, 22, 19, 16, 15, 14] },
  { id: 19, name: 'Blacksmith', ratios: [12, 10, 8, 6, 4, 2] },
  { id: 20, name: 'Necromancer', ratios: [20, 19, 18, 17, 16, 16] },
  { id: 21, name: 'Couriers', ratios: [19, 18, 17, 15, 13, 11] },
  { id: 22, name: 'Brothel', ratios: [17, 15, 13, 11, 9, 7] },
  { id: 23, name: 'Land Sales', ratios: [16, 15, 13, 10, 8, 6] },
  { id: 24, name: 'Carpenter', ratios: [15, 13, 10, 8, 6, 4] },
  { id: 25, name: "Entertainer's Guild ", ratios: [20, 18, 16, 13, 11, 9] },
  { id: 26, name: 'Healer', ratios: [18, 15, 12, 10, 7, 4] },
  { id: 27, name: 'Port (if coastal)', ratios: [19, 18, 16, 14, 12, 10] },
  { id: 28, name: "Worker's Union", ratios: [19, 18, 16, 11, 9, 7] },
  { id: 29, name: 'Stonemason', ratios: [18, 15, 12, 10, 7, 4] },
  { id: 30, name: 'University', ratios: [22, 20, 18, 16, 14, 12] },
  { id: 31, name: 'Mercenaries', ratios: [19, 18, 17, 16, 14, 12] },
]

export const settlementServiceActions: Pick<SettlementService, 'id' | 'name' | 'actions'>[] = [
  { id: 0, name: 'Inn / Tavern', actions: [] },
  { id: 1, name: 'Adventuring Supplies', actions: [] },
  { id: 2, name: 'Animals and Mounts', actions: [] },
  { id: 3, name: 'Books and Maps', actions: [] },
  { id: 4, name: 'Jewelry trader', actions: [] },
  { id: 5, name: 'Armourer', actions: [] },
  { id: 6, name: 'Bank', actions: [] },
  { id: 7, name: 'Finesmith', actions: [] },
  { id: 8, name: 'Tailor', actions: [] },
  { id: 9, name: 'Potions, poisons, herbs', actions: [] },
  { id: 10, name: 'Religious idols & Blessings', actions: [] },
  { id: 11, name: 'Food & drink seller', actions: [] },
  { id: 12, name: 'Temple', actions: [] },
  { id: 13, name: 'Spell tomes and scrolls', actions: [] },
  { id: 14, name: 'Thieving supplies', actions: [] },
  { id: 15, name: 'Weapons Shop', actions: [] },
  { id: 16, name: 'Vehicles and transportation', actions: [] },
  { id: 17, name: "Adventurer's Guild", actions: [] },
  { id: 18, name: 'Magic Items', actions: [] },
  { id: 19, name: 'Blacksmith', actions: [] },
  { id: 20, name: 'Necromancer', actions: [] },
  { id: 21, name: 'Couriers', actions: [] },
  { id: 22, name: 'Brothel', actions: [] },
  { id: 23, name: 'Land Sales', actions: [] },
  { id: 24, name: 'Carpenter', actions: [] },
  { id: 25, name: "Entertainer's Guild ", actions: [] },
  { id: 26, name: 'Healer', actions: [] },
  { id: 27, name: 'Port (if coastal)', actions: [] },
  { id: 28, name: "Worker's Union", actions: [] },
  { id: 29, name: 'Stonemason', actions: [] },
  { id: 30, name: 'University', actions: [] },
  { id: 31, name: 'Mercenaries', actions: [] },
]
